# Generated by Django 5.1.1 on 2025-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Outros', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='installment_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='São Paulo, SP', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pay_online',
            field=models.BooleanField(default=False),
        ),
    ]
