# Generated by Django 5.2.1 on 2025-05-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_installment_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='bairro',
            field=models.CharField(default='Santos Dumont', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='Antiguidades', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='cidade',
            field=models.CharField(default='Maceió', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='estado_1',
            field=models.CharField(default='Alagoas', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='estado_2',
            field=models.CharField(default='Alagoas', max_length=50),
        ),
    ]
