# Generated by Django 5.2.1 on 2025-05-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('vara', models.CharField(max_length=100)),
                ('comarca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('data_recebimento', models.DateField()),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.advogado')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.parte')),
            ],
        ),
    ]
